### ISSUE TITLE
Error: Insufficient balance

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leapdao-integ-tests#11]
tests fail in 4

```
Running:  4_epochLengthExit.js
╔══════════════════════════════════════════╗
║   Test: Exit after epochLength change    ║
║Steps:                                    ║
║1. Deposit to Alice                       ║
║2. Trasfer from Alice to Bob              ║
║3. Change epochLength                     ║
║4. Exit Bob                               ║
╚══════════════════════════════════════════╝
------Will mint and deposit 10000000 tokens for 0xebdd18d3e6e8f0b8569ad9de169bb7bd19f088e2------
Minting token to account 0xebdd18d3e6e8f0b8569ad9de169bb7bd19f088e2...
Aprroving 10000000 tokens for deposit...
Depositing 10000000 tokens...
0xebdd18d3e6e8f0b8569ad9de169bb7bd19f088e2 balance after deposit: 0
------Transfer from Alice to Bob------
------Transfering 5071 tokens from 0xebdd18d3e6e8f0b8569ad9de169bb7bd19f088e2 to 0x7cf78a2cf5a105a7312dc67f242e25264440e753------
------Balances before------
{ '0':
   { '0xced6cec7891276e58d9434426831709fcbdd0c49': '200000000000',
     '0x2b2b598faba3661c2e4eaa75f9e6a111d860a86d': '0',
     '0xa237080c6c98bcddf2125ce2bc40f6f528a5f024': '95958',
     '0x22573f218b8559f8345ae49f0bcf8f798d0d2685': '413',
     '0x7f4474e43affbc0166d7e6bc08ef38850c166abf': '968',
     '0x7cf78a2cf5a105a7312dc67f242e25264440e753': '0' } }
(node:45806) UnhandledPromiseRejectionWarning: Error: Insufficient balance
    at makeTransfer (/Users/johann/dev/leapdao-integ-tests/src/helpers.js:61:11)
    at transfer (/Users/johann/dev/leapdao-integ-tests/tests/actions/transfer.js:11:22)
```

node 1 logs:
```

2019-01-29T06:36:34.170Z leap-node Height: 130, epoch: 2, epochLength: 2
2019-01-29T06:36:34.171Z tendermint I[29016-01-29|07:36:34.171] Committed state                              module=state height=129 txs=0 appHash=EE08FF25DB43D8A8DF0B0A7E1913D22ABE719128C9DD03A5687D334E02C274DD

2019-01-29T06:36:34.679Z tendermint E[29016-01-29|07:36:34.677] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"

2019-01-29T06:36:34.688Z leap-node:error Deposit ID skipping ahead. want 45, found 49
2019-01-29T06:36:35.688Z leap-node:error Deposit ID skipping ahead. want 45, found 50
2019-01-29T06:36:35.689Z leap-node:error Deposit ID skipping ahead. want 45, found 49
2019-01-29T06:36:36.689Z leap-node:error Deposit ID skipping ahead. want 45, found 50
2019-01-29T06:36:36.690Z leap-node:error Deposit ID skipping ahead. want 45, found 51
```

**Comment by troggy** [comment]
"fixed" with band-aid here https://github.com/leapdao/leapdao-integ-tests/commit/0f5ab3b5891257e887c65eb14077fe4f8f31dd68
