### ISSUE TITLE
"Cannot call fallback function from the proxy admin" when running tests

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leapdao-integ-tests#6]
`yarn run test` produces in `node0.out`:

```
2018-12-27T09:27:46.570Z leap-node Syncing events...
unhandledRejection Error: Returned error: VM Exception while processing transaction: revert Cannot call fallback function from the proxy admin
    at Object.ErrorResponse (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/johann/dev/leapdao-integ-tests/build/node/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/web3-providers-http/src/index.js:91:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by troggy** [comment]
@johannbarbie is it solved already?

**Comment by johannbarbie** [comment]
yes, the problem was that deployment script used `account[0]` to deploy proxies. i've reverted it here: https://github.com/leapdao/leap-contracts/commit/a0d5d8e1744c4b865d683a616a60a232ed3bdd98  and that solved it.
